---
INSERT_INTO:
  'INSERT INTO {table} ({col_names}) VALUES ({tuple_q_marks})'

INSERT_IN_FUNCTION:
  'INSERT INTO function (function_name) VALUES (?)'

INSERT_IN_USER:
  'INSERT INTO user (First_name, Surname, function, years_in_the_function) VALUES (?, ?, ?, ?)'

INSERT_IN_ANNOTATION: >
  INSERT INTO annotations (question, question_id, alt_question, passage, 
  answer, alt_answer, question_accepted, fluent, comprehensive, factual, annotator) 
  VALUES (?,?,?,?,?,?,?,?,?,?,?)


SELECT_ALL:
  'SELECT {column_names} FROM {table}'

SELECT_PK_FUNCTION:
  'SELECT Id FROM function WHERE function_name = "{function}"'

SELECT_PK_USER:
  'SELECT Id FROM user WHERE First_name = ? AND Surname = ? AND function = ? AND years_in_the_function = ?'

SELECT_LENGTH:
  'SELECT question_id FROM questions'

SELECT_QUESTION:
  'SELECT * FROM questions WHERE question_id = ?'

SELECT_JOIN: >
  SELECT question_id, FC.function_name FROM annotations as AN
  LEFT JOIN user as US ON AN.annotator = US.Id
  LEFT JOIN function as FC ON US.function = FC.Id
  WHERE AN.question_id = ?

DELETE_ROW:
  'DELETE FROM questions WHERE question_id = ?'